In [7]:
import numpy as np

In [8]:
!ls

Calibracao.ipynb            padrao_gabarito.png
Untitled.ipynb              padrao_perto_parede.png
neutral_color_wall.png      padrao_perto_parede_02.png
padrao_chao_meio_sala.png   visaorobo_puxa_vermelho.mp4
padrao_estante.png


## Imagem próxima à parede

Imagem padrao_perto_parede_02.png

<img src=padrao_perto_parede_02.png width=60%>

Selecting what should be white on Photoshop and taking a look at the histogram

<img src=./neutral_color_wall.png width=50%>

In [9]:
rgb = [238, 139, 84]

In [10]:
rgb_np = np.array(rgb)

In [17]:
np.round(rgb_np/255.0, 2)

array([0.93, 0.55, 0.33])

Imagem padrao_estante.png

<img src=padrao_estante.png width=60%>

<img src=neutral_color_locker.png width=60%>

In [20]:
rgb2 = [246, 180, 161]

In [21]:
rgb2_np = np.array(rgb2)

In [23]:
np.round(rgb2_np/255.0, 2)

array([0.96, 0.71, 0.63])

# Average of adjusted values

In [24]:
avg_np = (rgb_np + rgb2_np)/2

In [25]:
avg_np

array([242. , 159.5, 122.5])

In [27]:
np.round(avg_np/255, 2)

array([0.95, 0.63, 0.48])

# Extremos

In [29]:
np.round(rgb_np/255.0, 2)

array([0.93, 0.55, 0.33])

In [28]:
np.round(rgb2_np/255.0, 2)

array([0.96, 0.71, 0.63])